### ISSUE TITLE
[DE79]: Compilation Error in Opencenter Chef Single-Controller Role

### ISSUE THREAD

**Issue by seancarlisle** [rcbops/opencenter#488]
This resulted from the same session as issue #487.  After a second attempt to deploy using Opencenter failed, I instructed the user to blow away the Opencenter server and the Opencenter agent on their nodes.  This left a fully functioning chef server that I instructed them to use instead.  They changed the controller role from ha-controller1 to single-controller and tried to run chef-client on their controller.  This resulted in a "recipe compilation" error.  After issue #487 and this, the customer had to wipe and reload their environment.

**Comment by mancdaz** [comment]
Hi @seancarlisle 

the ha-controller1 role is designed to be used in opencenter in place of the single-controller role. Switching between roles on a server where chef-client has already run will indeed result in recipe compilation issues since certain node values will have been set that are not compatible with the way a different role works.  I am going to mark this 'not a bug', since this is inherently not something we can fix

**Comment by seancarlisle** [comment]
@mancdaz 

That makes sense, then.  Thanks for the quick response!
